sudo: required
language: node_js
os: windows
node_js:
  - '10'
branches:
  only:
  - 'dev'
  - 'master'
before_install:
  - 'sudo apt-get -y install codecov@3.7.0'
# install:
#   - 'npm install codecov'
script:
  - 'npm run cover'
  - 'codecov'

  # @3.7.0 after_success:


