sudo: required
language: node_js
os: windows
node_js:
  - '10'
branches:
  only:
  - 'dev'
  - 'master'
install:
  - 'npm install'
  - 'npm install -g codecov'
 after_success:
   - 'bash <(curl -s https://codecov.io/bash) -f coverage/coverage.json'
  script:
  - 'npm run cover'
  - 'codecov'
  - 'coverage'
