sudo: required
language: node_js
os: windows
node_js:
  - '10'
branches:
  only:
  - 'dev'
  - 'master'
install:
  - 'npm install codecov@3.7.0'
  script:
  - 'npm run cover'
  - 'codecov'


