sudo: required
language: node_js
os: windows
git:
  submodules:false
  before_install:
  - git submodule update --init --recursive
node_js:
  - '10'
install:
  - 'npm install'
  branches:
  only:
  - 'dev'
  - 'master'
  script:
  - 'npm run cover'