sudo: required
language: node_js
os: windows
git:
  submodules:false
  before_install:
  - git submodule update --init --recursive
node_js:
  - 'v10.15.3'
install:
  - 'npm install'
  brancher:
  only:
  - 'dev'
  - 'master'
  script:
  - 'npm run cover'