sudo: required
language: node_js
os: windows
node_js:
  - '10'
branches:
  only:
  - 'dev'
  - 'master'
install:
  - 'npm ci -g codecov'
  script:
  - 'npm run cover'
# after_success:
  - 'codecov'


