sudo: required
language: node_js
os: windows
node_js:
  - '10'
branches:
  only:
  - 'dev'
  - 'master'
install:
  - 'npm install'
  - 'npm install -g codecov'
  - 'pip install codecov'
  script:
  - 'npm run cover'
   after_success:
    - 'codecov'


